package client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"os"
	"time"
)

const defaultInferenceBaseURL = "http://localhost:3002"

// inferenceBaseURL returns the inference service base URL. It defaults to
// defaultInferenceBaseURL, and can be overridden via INFERENCE_API_BASE_URL
// (used by tests to point at a mock server).
func inferenceBaseURL() string {
	if v := os.Getenv("INFERENCE_API_BASE_URL"); v != "" {
		return v
	}
	return defaultInferenceBaseURL
}

var httpClient = &http.Client{Timeout: 10 * time.Second}

// ForwardImage sends the image to the inference service's image-receiving
// endpoint as multipart/form-data. It returns an error if the request could
// not be sent or the inference service responded with a non-2xx status.
func ForwardImage(file io.Reader, filename string) error {
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	part, err := writer.CreateFormFile("image", filename)
	if err != nil {
		return fmt.Errorf("create form file: %w", err)
	}
	if _, err := io.Copy(part, file); err != nil {
		return fmt.Errorf("copy image content: %w", err)
	}
	if err := writer.Close(); err != nil {
		return fmt.Errorf("close multipart writer: %w", err)
	}

	req, err := http.NewRequest(http.MethodPost, inferenceBaseURL()+"/internal/images", body)
	if err != nil {
		return fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", writer.FormDataContentType())

	resp, err := httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return fmt.Errorf("inference service returned status %d", resp.StatusCode)
	}

	return nil
}

// EmbeddingResponse is the embedding generated by the inference service for
// a single image.
type EmbeddingResponse struct {
	Dimension int       `json:"dimension"`
	Embedding []float64 `json:"embedding"`
}

// GenerateEmbedding sends the image to the inference service's embedding
// endpoint as multipart/form-data and returns the generated embedding. It
// returns an error if the request could not be sent, the inference service
// responded with a non-2xx status, or the response body could not be parsed.
func GenerateEmbedding(file io.Reader, filename string) (*EmbeddingResponse, error) {
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	part, err := writer.CreateFormFile("image", filename)
	if err != nil {
		return nil, fmt.Errorf("create form file: %w", err)
	}
	if _, err := io.Copy(part, file); err != nil {
		return nil, fmt.Errorf("copy image content: %w", err)
	}
	if err := writer.Close(); err != nil {
		return nil, fmt.Errorf("close multipart writer: %w", err)
	}

	req, err := http.NewRequest(http.MethodPost, inferenceBaseURL()+"/internal/embeddings", body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", writer.FormDataContentType())

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("inference service returned status %d", resp.StatusCode)
	}

	var embedding EmbeddingResponse
	if err := json.NewDecoder(resp.Body).Decode(&embedding); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}

	return &embedding, nil
}
